const Config = {
  BaseUrl: 'https://www.cuckooindia.in/cuckooApp/api/',
  BaseUrlNew: 'https://cuckoo.mcrm.in/API/',
  SendOtpApi: 'userOTP',
  UserLoginApi: 'userLogin',
  UserDetailApi: 'userDetail',
  UserProfileUpdateApi: 'userProfileupdate',
  StateListApi: 'stateList',
  DistrictListApi: 'districtList',
  CityListApi: 'cityList',
  AddUserAddressApi: 'addUserAddress',
  UserAddressListApi: 'userAddressList',
  FeedbackListApi: 'feedbackList',
  AddFeedbackApi: 'addFeedback',
  ReasonListApi: 'reasonList',
  RequestServiceApi: 'requestService',
  ProductRegisterApi: 'productRegister',
  RequestServiceListApi: 'requestServiceList',
  UserProductListApi: 'userProductList',
  GetSourceOfSale: 'getSourceOfSale',
  GetDistrict: 'getDistrict',
  DeleteUserAccount: 'deleteUserAccount',
};
export default Config;
