const Images = {
  logo: require('../Assets/images/logo.png'),
  userImg: require('../Assets/images/useruser.png'),
  registerImg: require('../Assets/images/reg.jpg'),
  productReg: require('../Assets/images/PR.jpg'),
  productReq: require('../Assets/images/PRR.jpg'),
  cuckooamc: require('../Assets/images/cuckooamc.jpg'),
  latedoffer: require('../Assets/images/latedoffer.jpg'),
  home: require('../Assets/images/home.png'),
  feedback: require('../Assets/images/Feedback.png'),
  rewards: require('../Assets/images/rewards.png'),
  profile: require('../Assets/images/Profile.png'),
  backIcon: require('../Assets/images/back.png'),
  arrowDown: require('../Assets/images/ArrowDown.png'),
  rightArrow: require('../Assets/images/RightArrow.png'),
  dateTime: require('../Assets/images/DateTime.png'),
  add: require('../Assets/images/add.png'),
  purchases: require('../Assets/images/purchases.png'),
  request: require('../Assets/images/request.png'),
  homeloca: require('../Assets/images/homeloca.png'),
  settingss: require('../Assets/images/settingss.png'),
  logout: require('../Assets/images/logout.png'),
  delete: require('../Assets/images/delete.png'),
  openCamara: require('../Assets/images/openCamara.png'),
  notification: require('../Assets/images/notification.png'),
  fedbackemail: require('../Assets/images/fedbackemail.png'),
  fedbackfeedback: require('../Assets/images/fedbackfeedback.png'),
  fedbackinformation: require('../Assets/images/fedbackinformation.png'),
  explorebackground: require('../Assets/images/explorebackground.png'),
  explorefrent: require('../Assets/images/explorefrent.png'),
  close: require('../Assets/images/close.png'),
  cuckooLogo: require('../Assets/logo.jpg'),
};
export default Images;
