const Strings = {
  welcome: 'Welcome!',
  requiredValidate: 'Phone Number/E-mail ID',
  enterPhoneNo: '(405)123-4567',
  enterNameEmail: 'Enter your name and email',
  firstLastName: 'First & Last name',
  signLoginwithMobNo: 'Signup or login to your account with your phone number.',
  btnSendOtp: 'send OTP',
  verificationCode: 'Verification code OTP',
  verificationTxt: 'A Verifaction code has been sent to : ',
  btnNext: 'Next',
  dassed: '----',
  ProductNamee: 'Product Name : ',
  Productreasonn: 'Product reason : ',
  Productremarkss: ' Product remarks : ',
  ProductDateTime: '  Product DateTime : ',
  helpsupport: 'Help & Support',
  NoAddressaddedd: ' No Address added',
  memberSince: 'Member since September,2022',
  next: 'Next',
  NoRequestsadded: 'No Requests added',
  rewardsPoints: 'Available Reward Points : ',
  cuckooRewards: 'Cuckoo Rewards',
  redeemNow: 'Redeem Now',
  useremail: 'prachi@digipanda@gmail.com',
  resentOTP: 'Resent OTP',
  changephoneEmail: 'Change phone Number',
  userName: 'Parmod Kumar',
  cuckooWelcomeTxt: 'Welcome to CUCKOO Service',
  registerNewProduct: 'Register New Pro...',
  installation: 'Installation',
  newProducts: 'New Products',
  reInstallation: 'Re-Installation',
  exisitingProducts: 'Exisiting Products',
  chooseProduct: 'Choose Product',
  purchasedData: 'Purchased Date',
  productSerialNumber: '08 - 12 Digit Product Serial number',
  serialNo: 'A2E3D5CE',
  serialNoo: 'Serial No :',
  Warrantyy: 'Warranty',
  Pleaseaddaddressfirst: 'Please add address first',
  NoListAvailable: 'No List Available',
  warrantycard: 'Warranty Card',
  invioce: 'Upload your Invioce',
  invioceUploaded: ' Invioce',
  purchasedfrom: 'Purchased from',
  browse: 'Browse',
  selectAddress: 'Select Address',
  addNewAddress: 'Add New Address',
  existing: 'Existing',
  myAddress: 'My Address',
  btnSubmit: 'SUBMIT',
  address: 'Address',
  selecteCountry: 'Select Country',
  country: 'Country',
  state: 'State',
  district: 'District',
  city: 'City',
  pinCode: 'Pincode',
  entrePinCode: 'Entre Pin Code of 6 Character ',
  preferredDate: 'Preferred Date and Time',
  remarks: 'Remarks',
  requestService: 'Request Ser..',
  pleaseSelectReason: 'Please select the Reason',
  feedbackdoc: 'Feedback Doc',
  submitfeedback: 'Submit your feedback',
  listofSubmitted: 'List Of Submitted Feedbacks',
  feedback: 'Feedback',
  profile: 'Profile',
  myProfile: 'My Profile',
  myPurchases: 'My Purchases',
  requests: 'Requests',
  pickFrom: 'Pick from the following ',
  addresses: 'Addresses',
  settings: 'Settings',
  logout: 'Logout',
  deleteAccount: 'Delete Account',
  editProfile: 'Edit Profile',
  fullname: 'Full Name',
  fullnamee: 'Pamrxxxxxx kuxxxxxx',
  email: 'Email',
  emaill: 'xyz gmail.com',
  phone: 'Phone ',
  phonee: '7823XXXXXX ',
  gender: 'Gender ',
  save: 'Save',
  register: 'Register...',
  serviceReq: 'Service Re...',
  requestforService: 'Request for Service',
  title: 'Title',
  privacy: 'Privacy',
  changepass: 'Change password',
  logoutAlt: 'are you want to Logout ',
  deleteAcc: 'are you want to Delete Account ',
  cancle: 'Cancle',
  ok: 'Ok',
  contectus: 'Contact us',
  faq: 'FAQs',
  addNewAddressAns: 'D-111, Noida Sector 63',
  edit: 'Edit',
  productRegistration: 'Product Registration',
  requestservice: 'Request for Service',
  buyCuckooAmc: 'Buy Cuckoo AMC',
  chackOffers: 'Check Latest Offers',
  chooseModel: 'Choose Model',
  exploreCuckoo: ` Explore Cuckoo's`,
  shopNow: 'SHOP NOW',
  productRange: 'Product Range',
  productRange: 'Product Range',
  product: 'Product :',
  requestReason: 'Request Reason :',
  preferredDateandTime: 'Preferred Date and Time :',
  remark: ' Remark : ',
  remark: ' Remark : ',
  house: ' House/Flat/Office No ',
  roadname: ' Road Name/Area/Colony ',
};
export default Strings;
