const StringsName = {
  dashborad: 'Dashboard',
  userWelcome: 'Hii, ',
  userName: 'Parmod',
  searchResturent: 'Search Your Resturent Quickly !',
  order: 'Orders',
  customer: 'Customers',
  dishes: 'Dishes',
  orderCount: '123',
  customerCount: '423',
  dishesCount: '323',
  deliverd: 'Deliverd',
  deliverdCount: '23',
  ongoing: 'Ongoing',
  ongoingCount: '16',
  pending: 'Pending',
  pendingCount: '15',
  jan: 'Jan',
  feb: 'Feb',
  mar: 'Mar',
  apr: 'Apr',
  jun: 'Jun',
  sales: 'Sales',
  profile: 'Profile',
  customerRatings: 'Customers Rating',
  lastMonths: 'In last Month',
  ratingCount: 'Based on 234 Rating',
  horizontalDasseline:
    '- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -',
  foodemenu: 'FoodMenu',
  rating38: '3.8',
};
export default StringsName;
